$e = [char]0x1b

Write-Host ""
Write-Host "$e[36m  +==============================================================+"
Write-Host "$e[36m  |              PowerShell 7 Architecture                       |"
Write-Host "$e[36m  +==============================================================+$e[0m"
Write-Host ""
Write-Host "$e[33m                            +-----------------+$e[0m"
Write-Host "$e[32m                            |   User Terminal |$e[0m"
Write-Host "$e[32m                            | (GoLand / VSCode|$e[0m"
Write-Host "$e[33m                            +--------+--------+$e[0m"
Write-Host "$e[33m                                     |$e[0m"
Write-Host "$e[33m                                     v$e[0m"
Write-Host "$e[36m                      +-----------------------------+$e[0m"
Write-Host "$e[35m                      |        PSReadLine           |$e[0m"
Write-Host "$e[35m                      | (Syntax HL / Predictive)    |$e[0m"
Write-Host "$e[36m                      +-------------+---------------+$e[0m"
Write-Host "$e[33m                                    |$e[0m"
Write-Host "$e[33m                                    v$e[0m"
Write-Host "$e[36m            +----------------------------------------------+$e[0m"
Write-Host "$e[37m            |            PowerShell 7 Core                 |$e[0m"
Write-Host "$e[36m            |   +-----------+      +-----------+           |$e[0m"
Write-Host "$e[34m            |   |  Parser   |      | Compiler  |           |$e[0m"
Write-Host "$e[36m            |   +-----+-----+      +-----+-----+           |$e[0m"
Write-Host "$e[36m            |         |                  |                  |$e[0m"
Write-Host "$e[36m            |         +--------+---------+                  |$e[0m"
Write-Host "$e[36m            |                  v                            |$e[0m"
Write-Host "$e[36m            |          +---------------+                    |$e[0m"
Write-Host "$e[32m            |          |    Engine     |                    |$e[0m"
Write-Host "$e[32m            |          |  (Pipeline)   |                    |$e[0m"
Write-Host "$e[36m            |          +---------------+                    |$e[0m"
Write-Host "$e[36m            +-----------------------+----------------------+$e[0m"
Write-Host "$e[33m                                    |$e[0m"
Write-Host "$e[33m               +--------------------+--------------------+$e[0m"
Write-Host "$e[33m               |                    |                    |$e[0m"
Write-Host "$e[33m               v                    v                    v$e[0m"
Write-Host "$e[36m       +---------------+    +---------------+    +---------------+$e[0m"
Write-Host "$e[31m       |   Cmdlets     |$e[0m    $e[31m|   Modules     |$e[0m    $e[31m|   .NET API    |$e[0m"
Write-Host "$e[31m       | (Built-in)    |$e[0m    $e[31m| (Extensions)  |$e[0m    $e[31m| (Core 8/9)    |$e[0m"
Write-Host "$e[36m       +---------------+    +---------------+    +---------------+$e[0m"
Write-Host ""